version: 1.0.0.{build}

environment:
  GithubEmail: notafiscalnet@gmail.com
  GithubUsername: NotaFiscal.net
  GithubPersonalAccessToken:
    secure: xDwP76rtY02prdj3ok14WISThtpw7pK4auHyTERwXGz3cqFLsorP0wJyEIDUu6UP

init:
- ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

skip_tags: true

configuration: Release

clone_depth: 3

before_build:
- cmd: nuget restore

build:
  verbosity: minimal

after_build:
- cmd: 7z a NotaFiscalNet.zip %APPVEYOR_BUILD_FOLDER%\src\NotaFiscalNet.Core\bin\%CONFIGURATION%\NotaFiscalNet*.dll

artifacts:
- path: NotaFiscalNet.zip
  name: NotaFiscalNet

after_test:
- ps: ./build-docs.ps1 $env:APPVEYOR_BUILD_FOLDER $env:APPVEYOR_BUILD_VERSION $env:GithubEmail $env:GithubUsername $env:GithubPersonalAccessToken

on_finish:
- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))